### ISSUE TITLE
False W002 error

### ISSUE THREAD

**Issue by JeyKeu** [twbs/bootlint#230] opened 2015-02-14 19:51 UTC
This works:

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge />
```
Whereas this does not:

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
```

`,chrome=1` causes bootlint to complain.

**Comment by cvrebert** [comment] 2015-02-14 19:57
Duplicate of #152.

**Closed by cvrebert** 2015-02-14 19:57 UTC
