### ISSUE TITLE
Any updates planned for Bootstrap 4?

### ISSUE THREAD

**Issue by ConduciveMammal** [twbs/bootlint#396] opened 2017-02-06 10:36 UTC
I understand BS4 is still in it's alpha stages so was just wondering if this will be updated anytime soon to support the new BS classes? Maybe even as a separate tool altogether?.

Thanks.

**Comment by hebbet** [comment] 2017-02-06 10:39
see #304

**Comment by zacechola** [comment] 2017-02-08 15:35
Closing as duplicate of #304, but the answer is yes, eventually.

**Closed by zacechola** 2017-02-08 15:35 UTC
