### ISSUE TITLE
W002 false positive

### ISSUE THREAD

**Issue by jwieder** [twbs/bootlint#302] opened 2015-08-13 05:43 UTC
W002 announces when meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" is used. Removing chrome=1 removes the W002 error, despite irrelevancy. Parse parse (or if you dont have time let me know and I can resole).

In looking at this I came across this series of issues with this tag and its relationship within <head> that I thought was interesting: https://github.com/h5bp/html5-boilerplate/issues/378

It might be cool to extend this warning to review <head> content order to see if the IE compatibility view bugs would be thrown.

**Comment by zacechola** [comment] 2015-08-17 13:41
This is a false positive, for sure, but probably a useful one. Chrome stopped supporting Chrome Frame in February 2014. Catching compat bugs is probably also outside the scope of Bootlint.

This might be something where we look at documenting it specifically. Thoughts, @hnrch02 and @cvrebert?

**Comment by cvrebert** [comment] 2015-08-17 17:29
Duplicate of #152.

**Closed by cvrebert** 2015-08-17 17:29 UTC

**Comment by jwieder** [comment] 2015-08-17 20:11
I understand its deprecated. 

The issue is that the error created is not accurate, and it would shouldnt be difficult to generate a separate (accurate) error message. I would be happy to take a look and push something that would hopefully resolve it. I understand its low priority, but its certainly not "invalid".
